[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "0.2.0-beta.4"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
